version: '3.1'

services:
  web:
    image: hexterror/library-runner:7.3.28
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
  db:
    image: hexterror/library-mysql:1.0
    restart: always
    ports:
      - 3306
  adminer:
    image: adminer:4.7.8
    restart: always
    ports:
      - 8081:8080
